### ISSUE TITLE
-resume option not working properly

### ISSUE THREAD

**Issue by hero2017** [gvreuls/cutechess#1]
It seems whenever I start a new tournament and then stop it after at least the 1st game is finished, it no longer updates the match pgn when I use the -resume option. 

The crosstable and schedule txt files are updated and live.pgn is always created but after resuming a tournament the match pgn still shows only the 1st game, even when the tournament is finished.

Is -resume broken? Or am I doing something wrong?

**Comment by gvreuls** [comment]
You're right, this is a bug. The fix is coming up right away, thank you for reporting.

**Comment by hero2017** [comment]
Thank you for the quick fix. I did a quick short test and it seems to be working now.
