### ISSUE TITLE
Add "Event" header to schedule and results json

### ISSUE THREAD

**Issue by ghost** [gvreuls/cutechess#3]
Pretty please. :)

**Comment by gvreuls** [comment]
The cross table JSON layout is an object so adding  an "Event" field to it isn't intrusive and won't break the web GUI. The schedule JSON layout is a list, so adding an "Event" field to it requires changing the layout to an object containing the "Event" field and a "Schedule" list.

IOW adding the "Event" field to the schedule JSON will break the schedule in the web GUI while just adding it to the cross table JSON won't cause any problems with the web GUI, so do you want it in the schedule too, or just in the cross table?

**Comment by gvreuls** [comment]
I have implemented the feature. It's only in the cross table for now, if you want it in the schedule too just let me know.

I'm going to leave this open for a few days.

**Comment by gvreuls** [comment]
Since this is output for the new web GUI, which seems dead for good, I'm closing this one.

Pulling the new GUI, and the state the old GUI is in after just a few days without maintenance, took my motivation for this project too. Sorry.
